### ISSUE TITLE
sttr, epe is tool large

### ISSUE THREAD

**Issue by arminghz** [XiandaGuo/OpenStereo#62]
hi, i have downloaded your pretrained model, in a test of sttr model, there is a error when load the checkpoint file, i ignore this error, at last, the epe is 49(px).

**Comment by duanyiqun** [comment]
Hi there, the too large epe problem may leaded by the error apears when loading. EPE 49 is not aligned with our local experiments. 

It is noted that sttr's best performance is achieved using extra occulsion label to train and only calculate the EPE within the occlusion area compared to other models. It means it should use flying3d subset instead of sceneflow original.  Currently we are releasing the Flying3D configs for sttr in next few weeks. We will also update the checkpoints at that time. 

Best regards

**Comment by XiandaGuo** [comment]
The training and evaluation of the STTR model have been fixed. The new checkpoint has been uploaded, and the training YAML has also been modified. Thank you again for identifying this issue.
